### PR TITLE
Organize, clean-up and some changes

### PR DESCRIPTION
**Pull request by miracle091**
Cleanup all files using CodeMaid
Moved all the "libs" to the folder named "Libs"
WatchDirectory now is dinamyc, is based on the OS versions and work with Vista and up (XP for now is not supported, i need to find a fallback solution)
Little visual changes to the SettingsForm

### CODE REVIEW

**Comment by metalex9** [comment]
Wow, I can't believe someone else found this, let alone bothered to help. Thank you! I'll check this out later when I have some time later.

**Comment by miracle091** [comment]
Don't pull this for the moment, i have to adapt it to your changes

**Comment by miracle091** [comment]
Now can be pulled, if you want.
Have added a class for log the errors when it's called. Anyway is all written in the commit.

**Comment by metalex9** [comment]
I think I'd like to reserve a "Libs" folder for any 3rd-party dlls in case I want to add any later, as I'd prefer to not have code I'm maintaining in the same folder as external dlls. I'll probably leave the classes where they are for now, though I agree they're not in the best place.

**Comment by metalex9** [comment]
I'm going to create some conflicts again. Don't worry about fixing this, I'll do a manual merge so you don't have to do it again.

**Comment by miracle091** [comment]
Ok Thanks! Anyway check the WatchDirectory at every start, but if not null/empty don't change it

**Pull request merged**
